#Use the official OpenJDK 17 image
FROM OpenJDK:17

LABEL author="ITasCode"
LABEL Org="DevTeam"

# Download the Spring PetClinic JAR file
RUN curl -o spring-petclinic-2.4.2.jar https://springjar-bucket.s3.amazonaws.com/spring-petclinic-2.4.2.jar

# Expose port 8080
EXPOSE 8080

# Run the Spring PetClinic application
CMD [ "java", "-jar", "spring-petclinic-2.4.2.jar" ]