version: "3.1"
services:
  web:
    image: nginx
    ports:
      - "6080:80"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=composedocker

#this file is used for installation of nginx and postgres sql...